#!/bin/sh

echo "****Running pre-commit hooks****"
# Keep staged changes and put unstaged aside for the hook (bypass hook to avoid recursion)
git commit --no-verify --message "WIP"
git stash -u
git reset --soft HEAD^

echo "**Applying spotless**"
if ! ./gradlew spotlessApply; then
  # Restore unstaged changes
  git stash pop -q
  exit $?
fi
# Add Spotless changes
git add -A

# Restore unstaged changes
git stash pop -q
echo "****Done pre-commit hooks****"