name: Docker Publish

on:
  push:
    branches:
      - 'develop'
      - 'master'

env:
  JAVA_VERSION: 21

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and Publish Docker Image
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: ./gradlew jib
      - name: Re-Deploy
        run: "curl -H 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}' https://togetherjava.org:5003/v1/update"
