name: Spotless

on: [push, pull_request_target]

jobs:
  autostlye:
    name: "Spotless"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ secrets.JAVA_VERSION }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check
        run: ./gradlew spotlessCheck
